### PR TITLE
tech-debt: Remove common lib from emily handler dependencies.

### PR DESCRIPTION
**Pull request by AshtonStephens**
## Remove common lib from emily handler dependencies.

resolves: #357

The Emily API needs to be able to compile for an AWS Lambda, but one of the dependencies , `sha2-asm`, can't compile for the aws arm lambda. The API will likely need access to the common library in the future in order to use the transaction library, but for now this ticket removes the common dependency.

The following is the dependency tree when `sbtc` is a dependency of the API:

```
sha2-asm v0.6.4
└── sha2 v0.10.8
    ├── aws-sigv4 v1.2.2
    │   └── aws-runtime v1.3.0
    │       ├── aws-config v1.5.3
    │       │   └── emily-handler v0.1.0 (/Users/ashtonstephens/workplace/sbtc/emily/handler)
    │       ├── aws-sdk-dynamodb v1.36.0
    │       │   ├── emily-handler v0.1.0 (/Users/ashtonstephens/workplace/sbtc/emily/handler)
    │       │   └── serde_dynamo v4.2.14
    │       │       └── emily-handler v0.1.0 (/Users/ashtonstephens/workplace/sbtc/emily/handler)
    │       ├── aws-sdk-sso v1.33.0
    │       │   └── aws-config v1.5.3 (*)
    │       ├── aws-sdk-ssooidc v1.34.0
    │       │   └── aws-config v1.5.3 (*)
    │       └── aws-sdk-sts v1.33.0
    │           └── aws-config v1.5.3 (*)
    ├── ed25519-dalek v2.1.1
    │   └── stacks-common v0.0.1 (https://github.com/Trust-Machines/stacks-blockchain/?branch=develop-upstream#6ca747f0)
    │       ├── clarity v0.0.1 (https://github.com/Trust-Machines/stacks-blockchain/?branch=develop-upstream#6ca747f0)
    │       │   └── sbtc v0.1.0 (/Users/ashtonstephens/workplace/sbtc/sbtc)
    │       │       └── emily-handler v0.1.0 (/Users/ashtonstephens/workplace/sbtc/emily/handler)
    │       └── sbtc v0.1.0 (/Users/ashtonstephens/workplace/sbtc/sbtc) (*)
    ├── p256k1 v7.1.0
    │   └── wsts v9.1.0
    │       └── stacks-common v0.0.1 (https://github.com/Trust-Machines/stacks-blockchain/?branch=develop-upstream#6ca747f0) (*)
    ├── stacks-common v0.0.1 (https://github.com/Trust-Machines/stacks-blockchain/?branch=develop-upstream#6ca747f0) (*)
    └── wsts v9.1.0 (*)
```

### CODE REVIEW

**Review by djordon — APPROVED** [review]
Looks good.

**Comment by djordon** [comment]
Wait, I think I have a fix

**Comment by djordon** [comment]
Nope never mind, it requires a change to stacks-core upstream.

**Comment by AshtonStephens** [comment]
Intentional tech debt, made this ticket:
- https://github.com/stacks-network/sbtc/issues/360

**Pull request merged**
