### PR TITLE
Replace rs_merkle with new implementation

### LINKED ISSUE #217: [sBTC DR] Incorrect merkle proof for block with 11 txs
### Expected Behavior
Merkle proof should be the same as on https://bridge.sbtc.tech/proofs?net=testnet

### Actual Behavior
The last leave in the merkle proof is different

### Steps to Reproduce

Run unit test in https://github.com/stacks-network/sbtc/pull/218

### PR DESCRIPTION
**Pull request by friedger**
## Summary of Changes

The crate rs_merkle does not implement the merkle tree as defined for bitcoin. A layer with an odd number of elements would return the last item unhashed.

This PR replaces rs_merkle with a new implementation by @jcnelson (thank you).

This PR fixes #217 

Some research results for information:
* `rs_merkle` does not complies with bitcoin
* `bitcoin::merkle_tree` does not provide a proof
* `stacks-common` Merkle tree is only for stacks using tagged data.

### Risks

There are a few unit tests that rely on the correct implementation of the merkle tree. However, all of them didn't catch the case described in #217. The new implementation might have other bugs not covered by the current unit tests. However, the risk is low as the code is covered by tests.
 

### How were these changes tested?

A new unit test was added covering the case described in #217 

### What future testing should occur?

More testing.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by AshtonStephens** [comment]
This PR seems to only add a test; how does is change the rs_merkle? Or is that coming in a follow up commit?

**Comment by friedger** [comment]
@AshtonStephens I need input about how to implement this. Maybe @jcnelson knows about a crate that implements merkle proofs for bitcoin or the best place where to implement it. It is a blocker for 0.1

**Comment by jcnelson** [comment]
You can easily generate a proof using `bitcoin::merkle_tree`.  If you're having trouble, I can write one for you once you're set on a Merkle tree implementation.

**Comment by friedger** [comment]
@jcnelson if bitcoin crate works, let's use. I didn't see how to access the different levels of the tree.

**Comment by friedger** [comment]
@jcnelson Not sure what you mean by `once you're set on a Merkle tree implementation.` I understand that `bitcoin::merkle_tree` is already an implementation.

**Comment by jcnelson** [comment]
@friedger Sorry, I may have misread what you said.  I thought you were looking for a Bitcoin Merkle tree implementation that could be used to generate and verify Merkle proofs?

**Comment by friedger** [comment]
@jcnelson yes, that is what we need. We need a correct implementation in ProofData

**Comment by friedger** [comment]
The code needs to be fix so that the unit test in this PR would pass

**Comment by jcnelson** [comment]
I will take a look at this.

**Comment by jcnelson** [comment]
Pushed a new merkle tree implementation that fixes these problems

**Comment by friedger** [comment]
@EmbeddedAndroid I merged main

**Review by CAGS295 — APPROVED** [review]

**Pull request merged**
