### PR TITLE
Add nightly cargo fmt rules

### PR DESCRIPTION
**Pull request by stjepangolemac**
Using nightly cargo fmt rules is a bit tricky as they won't work during normal `cargo fmt` calls. You need to specifically run `cargo +nightly fmt` for them to run.

Nevertheless, it will be good enough to run them from time to time. If you're able to add `+nightly` to your editors it'll run every time.

**Note**: Only one file is actually changed, the `rustfmt.toml`, everything else is automatically reformatted.

### CODE REVIEW

**Comment by AshtonStephens** [comment]
Were these changes made automatically? This is a pretty humongous PR - I assume it's all formatting?

**Comment by stjepangolemac** [comment]
Yeah it's all formatting, the only thing that I did manually is adding the `rustfmt.toml` file.

**Comment by friedger** [comment]
> Using nightly cargo fmt rules

Why when is that recommended?

**Comment by stjepangolemac** [comment]
Not sure I understand the questions. They're still unstable / in nightly but otherwise they work. There's a slight possibility they're not perfect but considering it's formatting it's pretty safe.

**Comment by stjepangolemac** [comment]
Just rebased this on latest master. When you have time please review. 🙏

**Review by friedger — APPROVED** [review]
LGTM

**Comment by stjepangolemac** [comment]
@friedger can you reapprove? I just got rid of some conflicts.

**Review by AshtonStephens — APPROVED** [review]
Approving based on the comment that:
1. this is only reformatting
2. regression tests would catch any oddities
3. the nightly build is trust able.

**Review by friedger — APPROVED** [review]
LGTM

**Comment by stjepangolemac** [comment]
Yep @AshtonStephens that's all true.

**Pull request merged**
