### PR TITLE
Add deployable contract

### LINKED ISSUE #142: Use asset.clar not in debug mode for devenv/testnet
There is a DEBUG flag in `asset.clar` that should be false for devenv and testnet

### PR DESCRIPTION
**Pull request by friedger**
## Description
This PR 
* introduces vitest/node to the asset-contract repo for use of clarinet-sdk.
* duplicates the clarity-bitcoin-mini contract to be used on devnet and testnet.
* changes the default deployment plan to use `clarity-bitcoin-mini-deploy.clar`
* fixes #142 

Ideally, this should be automated so that changes to the contract used for unit tests are applied to the deployable contract as well.

### CODE REVIEW

**Review by stjepangolemac — DISMISSED** [review]
As mentioned before, this looks very clunky and error prone but we're currently not aware of a better approach.

**Comment by friedger** [comment]
I have added a test to verify that the two versions only differ in the DEBUG flag

**Comment by stjepangolemac** [comment]
I'm feeling a bit uneasy about adding all these dependencies including yarn and vitest just to test that the contracts are the same. Could something like this be done with a simple bash script where we do a search and replace, then compare two files, and return an exit code of 0 if it's successful?

**Comment by friedger** [comment]
This is only the start of using clarinet-sdk. We will use it for unit tests and other things for clarity like error analysis or maybe formatting.

**Comment by friedger** [comment]
To me `asset-contract` is a development project in clarity that needs its toolchain. How do we get to a state were the code is a truth?

**Comment by CAGS295** [comment]
It is very subjective. It could be an older version that serves as "the oracle" in regression testing. e.g. a port, buggy or not, must maintain one-to-one compatibility. It could be an external component outside of your responsibility boundary. A concrete example is the bitcoind artifact. The methodology follows checksum + integration tests in the code-base native language (e.g., typescript for some of our repos-- rust + bash in this one). We don't bring C++ tooling to work with it. It could be archived data, corrupted, malformed, or dirty; it stays as is. It may be essential to keep the data untouched to maintain measurement/capture bias and avoid contamination, etc.

I don't know where the active development of those clarity contracts happens. It seems to me that it does not take place here. I don't know what policy you use to pull those contracts here. But that policy is most likely different from bringing the whole dev pipeline along with the contract. Do I make sense? We don't bring the whole compilation process, formatting, testing, etc., for bitcoind. Likewise, we should respect the responsibility boundary of our artifacts, even if it is source code we know and can manage.

I may be saying nonsense. My apologies if I work based on false assumptions. I'm still new around here. **TLDR**; Stjepan has a very valid point. As long as we are confident that the contract stays 'truthful' enough for its purpose, we don't need to worry about supporting its development.

**Comment by friedger** [comment]
It makes sense. 

However, the development does take place here. See issues and pull requests.

There is a similar discussion in the stacks-blockchain repo.

Is the solution a new repo sbtc-clarity? And stacks-blockchain-clarity? Where would the client be developed for these contracts? In cascading methodology or in parallel?

**Comment by CAGS295** [comment]
That changes everything, I support the changes then, lol. My last nitpick is why now? why everything together? It looks like we can split the PR into small PRs and discuss them individually.

**Comment by friedger** [comment]
I wanted to provide a solution to the issue with the debug flag. Two days ago, clarinet-sdk version 0.4.0 was released that provides enough features to replace the current code for testing in asset-contract

**Comment by friedger** [comment]
I'm happy to send two PRs.

**Comment by friedger** [comment]
Closing this in favour of #171

**Pull request closed without merging**
