### PR TITLE
Update daily.yml to fix `cargo audit`

### PR DESCRIPTION
**Pull request by jo-tm**
change order, upload artifact Cargo.lock first.

## Checklist
- [ ] Additions and modifications are documented
- [ ] Additions and modifications are tested

### CODE REVIEW

**Comment by jo-tm** [comment]
@AshtonStephens do you want to test this change on the `daily.yml` of `main` branch? Cannot run `daily.yml` from my working branch:

> The workflow must be committed to the default branch to be triggered. It won't work if you only commit it to a non-default branch.  (https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule)

**Comment by jo-tm** [comment]
other possible solution: https://github.com/tauri-apps/tauri/pull/692/files

**Comment by AshtonStephens** [comment]
> @AshtonStephens do you want to test this change on the `daily.yml` of `main` branch? Cannot run `daily.yml` from my working branch:
> 
> > The workflow must be committed to the default branch to be triggered. It won't work if you only commit it to a non-default branch.  (https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule)

What you could do is change this workflow to run when you push changes to `jo-tm/fix-cargo-audit` and comment out the subsequent job that publishes the code on crates.io while testing so that just the audit step runs. This will allow you to demo just the audit job. Once you know that works you can uncomment the publish step and then

**Comment by jo-tm** [comment]
removed JS audit because there is no js:

```
  audit-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: yarn audit
        working-directory: tooling/cli/node
        run: yarn audit
```

**Comment by jo-tm** [comment]
@AshtonStephens created a separated `audit.yml` that is running:

https://github.com/stacks-network/sbtc/actions/runs/6065315282
```bash
Warning: 3 vulnerabilities found!
Warning: 3 warnings found!
Found 3 advisory(ies), 2 unmaintained, 1 other
Warning: Unknown warning kind unsound found, please, file a bug
Error: Critical vulnerabilities were found, marking check as failed
```

**Comment by friedger** [comment]
@jo-tm There is a merge conflig and a failing check

**Review by AshtonStephens — CHANGES_REQUESTED** [review]
I'm not sure I understand this PR. I believe this is fixed by https://github.com/stacks-network/sbtc/pull/123?

**Comment by AshtonStephens** [comment]
Didn't receive update on this ticket for a while. Closing.

**Pull request closed without merging**
