### PR TITLE
Mine into wallet 1

### PR DESCRIPTION
**Pull request by CAGS295**
## Testing
```
> devenv$ up.sh
# Wait, or it will fail.
> devenv$ utils/deploy_contracts.sh
> devenv$ utils/mine_btc.sh 200
> devenv$ utils/deposit.sh
```
## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by friedger** [comment]
We still need some btc for withdrawal request for the deployer, don't we? 

I suggest to fund both wallets

**Comment by CAGS295** [comment]
I'm not sure. I haven't had issues with the deployer not having funds. Funding both sounds good. What happens with the accounts defined in the settings toml? Are those accounts ever funded somewhere? Can we fund accounts with clarinet as an extra step in the entry point?

**Comment by friedger** [comment]
The stx addresses are funded with millions of STX on launch

**Comment by friedger** [comment]
Is the deployer a bitcoin miner? Then we do not need to fund manually.

**Review by AshtonStephens — APPROVED** [review]

**Comment by CAGS295** [comment]
I am merging. @EmbeddedAndroid, can we change the miner service to mine into the deployer's wallet?

**Pull request merged**
