### PR TITLE
[sBTC DR] Add test for asset contract

### PR DESCRIPTION
**Pull request by friedger**
## Description
This PR 
* adds unit tests for the asset contract
* fixes https://github.com/stacks-network/sbtc/issues/103

See #79

### CODE REVIEW

**Comment by stjepangolemac** [comment]
I thought I've fixed this already. When I run `cargo make` locally I don't get this. @AshtonStephens should I see the same failures locally?

**Review by netrome — APPROVED** [review]
I'm pretty unfamiliar with Clarity testing, but as far as I can see this looks good! Thank you for adding these tests :pray:

**Comment by stjepangolemac** [comment]
@friedger confirmed this is based on latest master. These checks are passing for me locally but failing for him. 🤔

**Review by stjepangolemac — APPROVED** [review]
This looks good. My only suggestion is to consider moving the new `bin/` directory into the `asset-contract/` package as it only relates to that one.

**Review by stjepangolemac — DISMISSED** [review]

**Review by MarvinJanssen — APPROVED** [review]

**Review by setzeus — APPROVED** [review]
LGTM!

**Pull request merged**
