### PR TITLE
[sBTC DR] Add testnet deployment plan

### PR DESCRIPTION
**Pull request by friedger**
This PR
* adds a deployment plan for testnet

See #178 for instructions

### CODE REVIEW

**Comment by AshtonStephens** [comment]
How do we know that this works?

**Comment by friedger** [comment]
There is no unit test or the like. This can only be "tested" by running `clarinet deployments apply -p deployments/default.testnet-plan.yaml` with the credentials of `ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM`.

When we will deploy the contracts on testnet for the release the files need to be changed with the correct expected sender.

**Comment by radicleart** [comment]
Might be worth changing the contract owner after deployment to prevent someone randomly changing the public key using the default mnemonic?

**Comment by AshtonStephens** [comment]
> When we will deploy the contracts on testnet for the release the files need to be changed with the correct expected sender.
> 
> This PR is mainly to add as much of the deployment plan as possible today.

So I understand, running this is all that we need to do to "deploy" onto testnet...? I thought it was going to be more involved than that. Why is this feature so easy to deploy to testnet?

**Comment by friedger** [comment]
@AshtonStephens thank the clarinet team 😊

**Review by AshtonStephens — APPROVED** [review]

**Comment by friedger** [comment]
@radicleart The mnemonic needs to be defined by the user that calls this deployment plan. It needs to be defined in `settings/Testnet.toml`

**Review by setzeus — APPROVED** [review]

**Pull request merged**
