### PR TITLE
[romeo] Local devnet development

### PR DESCRIPTION
**Pull request by stjepangolemac**
Talk with bitcoind directly through RPC.

- [x] `Wallet` from `stacks-core` now generates correct Bitcoin regtest addresses when needed
- [x] `sbtc-cli` is now able to connect to arbitrary nodes (local devnet included 🎉 )
- [x] `romeo` is now able to connect and work with local devnet (if it runs electrum server and [this](https://github.com/stacks-network/sbtc/pull/114) does)
- [x] contract deployment is removed, it needs to be deployed before running romeo

### CODE REVIEW

**Comment by stjepangolemac** [comment]
Everything now works with [Tyler's docker setup](https://github.com/stacks-network/sbtc/pull/114). 🎉

**Review by friedger — APPROVED** [review]
LGTM

**Comment by radicleart** [comment]
Awesome work @stjepangolemac !

I'm hot on your heels... 

Just tried to create the devnet Hiro wallet address using the regtest net id and the (x-only) pubkey from settings/Devnet.toml 

```	
         net = { bech32: 'bcrt', pubKeyHash: 0x6f, scriptHash: 0xc4 }
	const addr = btc.Address(net).encode({type: 'tr', pubkey: xOnlyKey})
```

but could not reproduce the ordinal address. Did you manage this ?

NB I generated the public key for the deployer address using;

```
npx stx get_stacks_wallet_key "twice ... "
```

**Comment by stjepangolemac** [comment]
Not sure I fully understand the issue. Let's catch up tomorrow and figure it out.

**Pull request merged**
