### PR TITLE
CI: add workflow for lints

### LINKED ISSUE #143: CI: Add workflow for lints
We should add a github workflow for running `make lint`. In particular, code that produces Clippy warnings should not pass CI.

### PR DESCRIPTION
**Pull request by netrome**
closes #143

### CODE REVIEW

**Review by 8marz8 — APPROVED** [review]
lgtm!

**Comment by AshtonStephens** [comment]
Can we make this a step or part of the unit test workflow? It feels like the CI is duplicating work unnecessarily

**Comment by netrome** [comment]
> Can we make this a step or part of the unit test workflow? It feels like the CI is duplicating work unnecessarily
> 
> I'm wondering about the reasoning behind this choice. I recognize it's better not to muddy different workflows with different kinds of data but I bet there's a way to do some of this processing only once and still keep the errors clear.

Sure thing, I think that makes sense. I'll update.

**Comment by netrome** [comment]
> Can we make this a step or part of the unit test workflow? It feels like the CI is duplicating work unnecessarily
> 
> I'm wondering about the reasoning behind this choice. I recognize it's better not to muddy different workflows with different kinds of data but I bet there's a way to do some of this processing only once and still keep the errors clear.

Updated.

**Review by AshtonStephens — APPROVED** [review]

**Pull request merged**
