### PR TITLE
sbtc automatically deploy contracts

### PR DESCRIPTION
**Pull request by CAGS295**
## Summary of Changes

- New sbtc image: 291MB -> 939MB
- `up.sh` no longer builds images. Relates to #283 
-  `sbtc` service deploys contracts before running romeo. Conflicts with #215
- `mine_btc.sh` funds wallet 0. #222 #237

## Testing
```sh
> $cd devenv
> devenv$ ./build.sh
> devenv$ cd -
> $ ./down.sh && ./up.sh
# wait until the contracts are deployed
> $./logs.sh sbtc
[SIGINT] manual CTRL + C 
> $ cd utils
> utils$ ./mine_btc.sh 201
> utils$ ./deposit.sh
> utils$ ./withdraw.sh
```

Succesful sbtc logs look like:
```
Waiting on Stacks API http://stacks:20443/v2/info
Waiting on Stacks height 1
The following deployment plan will be applied:
---
id: 0
name: Devnet deployment
network: devnet
stacks-node: "http://stacks:20443"
bitcoin-node: "http://devnet:devnet@bitcoin:18443"
plan:
  batches:
    - id: 0
      transactions:
        - contract-publish:
            contract-name: clarity-bitcoin-mini
            expected-sender: ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM
            cost: 54370
            path: contracts/clarity-bitcoin-mini-deploy.clar
            anchor-block-only: true
            clarity-version: 2
        - contract-publish:
            contract-name: asset
            expected-sender: ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM
            cost: 38610
            path: contracts/asset.clar
            anchor-block-only: true
            clarity-version: 2
      epoch: "2.4"


Total cost:     0.00092980 STX
Duration:       1 blocks
~~~snip~~~
➡ Confirmed Publish ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.asset
➡ Confirmed Publish ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.clarity-bitcoin-mini
✔ Transactions successfully confirmed on Devnet
/
2023-10-17T00:00:21.164744Z  INFO electrum_client::raw_client: Trying to connect to 172.24.0.8:60401 (attempt 1/1) with timeout 10s    
2023-10-17T00:00:21.176515Z  INFO romeo::system: Starting replay of persisted events
2023-10-17T00:00:21.176631Z  INFO romeo::system: Replay finished with state: Uninitialized
2023-10-17T00:00:21.176640Z  INFO spawn: romeo::system: Spawning task=GetContractBlockHeight
2023-10-17T00:00:21.192556Z  INFO update: romeo::state: Processing event=ContractBlockHeight(2, 222)
2023-10-17T00:00:21.192566Z  INFO spawn: romeo::system: Spawning task=UpdateContractPublicKey
2023-10-17T00:00:21.204827Z  INFO update: romeo::state: Processing event=ContractPublicKeySetBroadcasted(2739ec19c92c552ce3d8d3beb8224da1729b7fa00604c8282d3cd5484d9acbe2)
```

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by CAGS295** [comment]
#283

**Comment by friedger** [comment]
> New sbtc image: 291MB -> 939MB

Where does the increase come from?

**Comment by stjepangolemac** [comment]
> > New sbtc image: 291MB -> 939MB
> 
> Where does the increase come from?

Final `sbtc` image seems like it went from alpine to bookworm-slim. Not a big deal but I would prefer to keep using alpine if anyhow possible.

**Review by friedger — APPROVED** [review]
Automatic contract deployment worked for me :-)

LGTM

**Review by stjepangolemac — APPROVED** [review]

**Comment by CAGS295** [comment]
Last time, I couldn't install clarinet on alpine. I will try again.

**Pull request merged**
