### PR TITLE
[sBTC DR] Run property-based tests with Vitest

### LINKED ISSUE #311: [sBTC DR] Property-based tests should run as part of the GitHub Actions
Switching to the Clarity SDK for property-based tests will allow them to run as part of the GitHub Actions covered by Vitest.

_Originally posted by @friedger in https://github.com/stacks-network/sbtc/issues/263#issuecomment-1757810044_

### PR DESCRIPTION
**Pull request by moodmosaic**
## Summary of Changes

Switching to the Clarity SDK allows the property-based tests for asset contract to run as part of the GitHub Actions covered by Vitest, as mentioned by @friedger in https://github.com/stacks-network/sbtc/issues/263#issuecomment-1757810044. This resolves #311.

```
> asset-contract@1.0.0 test
> vitest run

node_modules/@hirosystems/clarinet-sdk/vitest-helpers/src/vitest.setup.ts

 RUN  v0.34.6 C:/Snapshot/dev/stacks/sbtc/romeo/asset-contract

stdout | unknown test
init stacks simnet

stdout | tests/asset.test.ts > asset.clar: Invariant tests

STNH...MAZ6      get-balance ST2J...5NNC            0
ST1P...GZGM             mint ST2J...5NNC           39 bitcoin tx  0168...21cf
ST1P...GZGM get-total-supply                       39
ST1S...YPD5         transfer ST2N...87ND     37722781 (discarded)
ST3N...1XCP         transfer ST1S...YPD5     80362673 (discarded)
ST1S...YPD5 get-total-supply                       39
STNH...MAZ6      get-balance ST3A...GCS0            0
ST2C...K9AG get-total-supply                       39
ST2C...K9AG      get-balance ST1P...GZGM            0
ST1P...GZGM             mint ST2N...87ND           18 bitcoin tx  0168...21cf (expected, same bitcoin tx)
ST2C...K9AG      get-balance ST3N...1XCP            0
ST1P...GZGM             mint ST3P...YGKJ           72 bitcoin tx  0168...21cf (expected, same bitcoin tx)
ST1P...GZGM get-total-supply                       39
ST1P...GZGM             mint ST2J...5NNC           95 bitcoin tx  255d...a63c
ST2J...5NNC         transfer ST3A...GCS0    202204243 (discarded)

(...)

ST1P...GZGM             mint ST2C...K9AG           57 bitcoin tx  255d...a63c (expected, same bitcoin tx)
ST2R...P2VB get-total-supply                      134
ST2N...87ND get-total-supply                      134
ST2C...K9AG      get-balance STNH...MAZ6            0

 ✓ tests/asset.test.ts (5) 28704ms
 ✓ tests/clarity-bitcoin-mini-deploy.test.ts (1)

 Test Files  2 passed (2)
      Tests  6 passed (6)
   Start at  18:26:07
   Duration  33.68s (transform 345ms, setup 354ms, collect 748ms, tests 28.98s, environment 1.87s, prepare 467ms)
```

### Risks

The modified parts of the tests reflect the fact that I now use Clarinet SDK and Vitest to test, assert, and run the tests. In order to do that I had to [touch on existing tests](https://blog.ploeh.dk/2013/04/02/why-trust-tests/#b23efe23c1574f2b8ff85fb3c529ec9d) in order to remove the Deno reference(s). However, I've seen each test failing before making it pass, in order to avoid any [false positives](http://xunitpatterns.com/false%20positive.html).

### How were these changes tested?

Once you `cd` into `romeo/asset-contract` directory, you can run these tests via

```
npm install
npm test
```

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

(Let me know if there's a style guideline of this project that I can follow, and any changes to the documentation that I should make. There are no dependent changes in downstream modules.)

### CODE REVIEW

**Comment by moodmosaic** [comment]
Looks like tests are failing on CI, but they were all passing locally with `npm test`.

**Review by moodmosaic — COMMENTED** [review]
Ready for review.

**Review by hugocaillard — APPROVED** [review]
LGTM

**Review by AshtonStephens — APPROVED** [review]
Looks good.

**Pull request merged**
