### PR TITLE
Add necessary generated blocklist-api files to avoid build error

### LINKED ISSUE #192: Check in generated blocklist-api files
Without the generated blocklist-api source code, the signer compilation fails because the imported resources are missing. This is not an issue once `make build` is run locally, but to avoid making this an initial requirement, we should include the generated resources from the start.

### PR DESCRIPTION
**Pull request by 8marz8**
Closes #192 

Running `make build` locally fixes the build issue as it generates the files but this PR adds the necessary files so the signer crate build successfully without running `make build` as a requirment.

### CODE REVIEW

**Review by djordon — COMMENTED** [review]
I pulled this down and this fixed the issue of having VS Code complaining all the time by default, but running `make build` generates different diffs from what is here. Is that expected?

**Comment by 8marz8** [comment]
> I pulled this down and this fixed the issue of having VS Code complaining all the time by default, but running `make build` generates different diffs from what is here. Is that expected?

Yes, I intentionally didn't add all the files that get generated with `make build` and only included the necessary ones. 

I don't mind adding everything if that's preferred.

**Comment by djordon** [comment]
> > I pulled this down and this fixed the issue of having VS Code complaining all the time by default, but running `make build` generates different diffs from what is here. Is that expected?
> 
> Yes, I intentionally didn't add all the files that get generated with `make build` and only included the necessary ones.
> 
> I don't mind adding everything if that's preferred.

I actually meant that some of the files checked in here get changed by running `make build` on my machine. For example, `.generated-sources/blocklist-api/src/models/risk_severity.rs` gets changed to:
```diff
 use crate::models;
-use serde::{Deserialize, Serialize};

 /// RiskSeverity : Risk severity linked to an address
 /// Risk severity linked to an address
@@ -26,13 +25,13 @@ pub enum RiskSeverity {

 }

-impl std::fmt::Display for RiskSeverity {
-    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
+impl ToString for RiskSeverity {
+    fn to_string(&self) -> String {
         match self {
-            Self::Low => write!(f, "Low"),
-            Self::Medium => write!(f, "Medium"),
-            Self::High => write!(f, "High"),
-            Self::Severe => write!(f, "Severe"),
+            Self::Low => String::from("Low"),
+            Self::Medium => String::from("Medium"),
+            Self::High => String::from("High"),
+            Self::Severe => String::from("Severe"),
         }
     }
 }
```
Maybe this is caused by different versions of the OpenAPI generator or something?

As for whether all of the files should be checked in, I'm largely indifferent but I feel like there shouldn't be many diffs or additions when we run `make build`. Maybe we should `.gitignore` them?

**Comment by 8marz8** [comment]
> Maybe this is caused by different versions of the OpenAPI generator or something?
> 
> As for whether all of the files should be checked in, I'm largely indifferent but I feel like there shouldn't be many diffs or additions when we run `make build`. Maybe we should `.gitignore` them?

Oh interesting, I didn't expect that.
On my end, the .generated-resources is already ignored and unless I include `-f`, it doesn't get staged -- it's already included in .gitignore - [see](https://github.com/stacks-network/sbtc/blob/main/.gitignore#L3)

So if the files get overwritten by running `make build` locally, I don't think that's a problem and by default, they get ignored.

**Comment by djordon** [comment]
> > Maybe this is caused by different versions of the OpenAPI generator or something?
> > As for whether all of the files should be checked in, I'm largely indifferent but I feel like there shouldn't be many diffs or additions when we run `make build`. Maybe we should `.gitignore` them?
> 
> Oh interesting, I didn't expect that. On my end, the .generated-resources is already ignored and unless I include `-f`, it doesn't get staged -- it's already included in .gitignore - [see](https://github.com/stacks-network/sbtc/blob/main/.gitignore#L3)
> 
> So if the files get overwritten by running `make build` locally, I don't think that's a problem and by default, they get ignored.

Weird, my git isn't respecting it for some reason. I'll look into it later.

**Comment by netrome** [comment]
> So if the files get overwritten by running `make build` locally, I don't think that's a problem and by default, they get ignored.

Afaik, if files are checked in, git will still show diffs for them if you modify them no matter if they're covered by `.gitignore` or not.

**Comment by netrome** [comment]
> Maybe this is caused by different versions of the OpenAPI generator or something?

Perhaps. I tried running make build locally now and I'm getting identical files. Judging from your diff, I would guess you're running an older version (because implementing `Display` > `ToString`). 

Though if we check these files in, I think we should not rebuild them on `make build` by default.

@8marz8 - what do you think about breaking out the build of these files to a separate make target?

**Comment by 8marz8** [comment]
> @8marz8 - what do you think about breaking out the build of these files to a separate make target?

I'm okay with this - in this case, do you want me to check in all the generated files?

**Comment by netrome** [comment]
> I'm okay with this - in this case, do you want me to check in all the generated files?

I'd like to check in as few generated files as possible, so only the necessary ones is my preference.

**Comment by AshtonStephens** [comment]
What's the deal with this ticket?

**Comment by djordon** [comment]
Oh, we can close it. It's a "nice to have" allowing us to build the signer with just `cargo build` instead of requiring `make build` be run at least once. But it's unnecessary so we decided to de-prioritize it.

**Comment by djordon** [comment]
Closing for now. We will revisit this later.

**Pull request closed without merging**
