### PR TITLE
chore: add `flake.nix` including developer shell

### PR DESCRIPTION
**Pull request by aldur**
## Description

As someone who was configuring how to build this project for the first time, I thought it would be useful to have an easy way to install all build dependencies at once. I gave this a shot with `nix`. 

The result is that if you have `nix` installed and configured, you can run `nix develop` to enter a shell having all dependencies installed. Well, all except Smithy, who doesn't have a nix package yet.

Closes: ~NA~

## Changes

- Add `flake.nix` for development shells.

## Testing Information

- Install [`nix`](https://determinate.systems/posts/determinate-nix-installer/)
- Make sure you have flakes enabled (the installer linked above takes care of it, else see [here](https://nixos.wiki/wiki/Flakes))
- Run `nix develop`

## Checklist:

- [X] I have performed a self-review of my code
- [X] My changes generate no new warnings
- [ ] ~New and existing unit tests pass locally with my changes~
- [ ] ~Any dependent changes have been merged and published in downstream modules~

### CODE REVIEW

**Comment by cylewitruk** [comment]
Could you also update the repo readme with information on its (optional) use in the development workflow?

**Comment by cylewitruk** [comment]
Lgtm, but I'll tag @djordon and @matteojug for their opinions as well

**Comment by AshtonStephens** [comment]
Hey! Smithy shouldn't be used here anymore because we switched to using rust annotations to generate the Emily API template. Where are we needing this?

**Review by djordon — APPROVED** [review]
This looks good. I don't think we use Smithy anymore so I wouldn't worry about adding it, but I'll wait for @AshtonStephens to verify.

**Comment by aldur** [comment]
Oh, I wish I had read your comments before 7b8075c. I can make another commit and remove `smithy` from the README as well?

**Comment by AshtonStephens** [comment]
Yeah I'm sorry, I should have updated the readme at the same time as I removed it. Though, smithy is used to generate some of the CLIs that we pull in as crates - I'd assume there's not dependency on smithy for those but I'm wondering if you somehow got smithy related errors

**Comment by aldur** [comment]
> Yeah I'm sorry, I should have updated the readme at the same time as I removed it. Though, smithy is used to generate some of the CLIs that we pull in as crates - I'd assume there's not dependency on smithy for those but I'm wondering if you somehow got smithy related errors

Oh no I didn't (and was wondering why :)), but I still wanted to provide a full package.

**Comment by aldur** [comment]
> Have you tried the main make commands with the nix shell, do they all work (after installing Smithy manually)?

Yep, they all run. Three integration tests fail, but that does not seem related to my changes:

```txt
running 3 tests
test validation::minimal_push_check ... FAILED
test validation::op_csv_disabled ... FAILED
test validation::tx_validation_from_mempool ... FAILED

failures:

---- validation::minimal_push_check stdout ----
thread 'validation::minimal_push_check' panicked at sbtc/src/testing/regtest.rs:113:18:
called `Result::unwrap()` on an `Err` value: JsonRpc(Transport(SocketError(Os { code: 61, kind: ConnectionRefused, message: "Connection refused" })))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- validation::op_csv_disabled stdout ----
thread 'validation::op_csv_disabled' panicked at sbtc/src/testing/regtest.rs:113:18:
called `Result::unwrap()` on an `Err` value: JsonRpc(Transport(SocketError(Os { code: 61, kind: ConnectionRefused, message: "Connection refused" })))

---- validation::tx_validation_from_mempool stdout ----
thread 'validation::tx_validation_from_mempool' panicked at sbtc/src/testing/regtest.rs:113:18:
called `Result::unwrap()` on an `Err` value: JsonRpc(Transport(SocketError(Os { code: 61, kind: ConnectionRefused, message: "Connection refused" })))


failures:
    validation::minimal_push_check
    validation::op_csv_disabled
    validation::tx_validation_from_mempool

test result: FAILED. 0 passed; 3 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.02s
```

**Comment by cylewitruk** [comment]
> but that does not seem related to my changes

Yeah, you didn't change anything there so that's unrelated to you. The PR opener gets the honors of clicking "Squash and merge" in this repo :)

**Comment by cylewitruk** [comment]
> merged commit [2059739](https://github.com/stacks-network/sbtc/commit/20597390c5244b6c44c8f70fc441409307e43904) into main

Wow, not every day you get to see a fully-numeric commit hash (prefix) :)

**Pull request merged**
